"""empty message

Revision ID: 5ef9f85d3186
Revises: e86713612036
Create Date: 2024-01-23 10:15:29.104002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef9f85d3186'
down_revision = 'e86713612036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_table', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
