"""empty message

Revision ID: bf0123d1c7e2
Revises: ec9bff29441c
Create Date: 2024-01-23 12:13:39.427720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0123d1c7e2'
down_revision = 'ec9bff29441c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_table', schema=None) as batch_op:
        batch_op.drop_column('artist_name')

    # ### end Alembic commands ###
