"""empty message

Revision ID: ec9bff29441c
Revises: 28a8ef855844
Create Date: 2024-01-23 11:26:54.094871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9bff29441c'
down_revision = '28a8ef855844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(), nullable=True))
        batch_op.drop_column('comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
